name: Streamlit CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 . --ignore=E501,W503 --exclude=.venv,venv,__pycache__,.git

      - name: Run tests
        run: |
          if [ -d tests ]; then pytest -v; else echo "No tests directory found — skipping."; fi

      - name: Verify Streamlit starts
        run: |
          python -c "from streamlit.web import cli as stcli; import sys; sys.argv=['streamlit','run','streamlit_app.py','--headless']; sys.exit(stcli.main())" || echo "Streamlit check done."
